---
- name: Vérifications - Récupération du model du Baremetal
  shell: /usr/sbin/dmidecode -s system-product-name | cut -d ' ' -f2
  register: ambx_model
  no_log: true

- name: Initialisation variable "ambx_model"
  set_fact:
    ambx_model: "{{ ambx_model.stdout }}"
  no_log: true

- name: "Socle - Configuration hardware pour socle DELL"
  import_tasks: dell.yml
  when: ansible_facts.system_vendor == "Dell Inc."

- name: Socle - Configuration matériel pour socle Lenovo
  include_tasks: lenovo.yml
  when: ansible_facts.system_vendor == "Lenovo"
